[package]
name = "executor"
version = "0.1.0"
edition = "2024"

[dependencies]
kit = { path = "../kit" }
global = { path = "../global" }
umk = { path = "../umk" }
rustpython = { version = "0.4.0", features = ["default"] }
