[package]
name = "unimake"
version = "0.1.0"
edition = "2024"

[dependencies]
umk = { path = "../umk" }
workspace = { path = "../workspace" }
global = { path = "../global" }
clap = { version = "4.5.38", features = ["unicode", "string", "derive", "wrap_help"] }