[package]
name = "kit"
version = "0.1.0"
edition = "2024"

[dependencies]
global = { path = "../global" }
umk = { path = "../umk" }
ahash = "0.8.11"
rustpython = { version = "0.4.0", features = ["default"] }
rustpython-vm = "0.4.0"
